clc;
clear;
close all;
f = -80:0.01:80;
figure(1);
y = sign(dirac(f - 30)) + sign(dirac(f + 30)) / 3;
plot(f, y);
xlabel('f / Hz', 'fontsize', 16);
ylabel('|X_1(f)| / a.u.', 'fontsize', 16);
title('Amplitude spectrum', 'fontsize', 16);
figure(2);
plot(f, zeros(size(f)));
xlabel('f / Hz', 'fontsize', 16);
ylabel('\theta_1(f)', 'fontsize', 16);
title('Angular spectrum', 'fontsize', 16);
figure(3);
y = sign(dirac(f - 70)) - 3 / 5 * sign(dirac(f - 10));
plot(f, y);
xlabel('f / Hz', 'fontsize', 16);
ylabel('|X_2(f)| / a.u.');
title('Amplitude spectrum', 'fontsize', 16);
figure(4);
plot(f, zeros(size(f)));
xlabel('f / Hz', 'fontsize', 16);
ylabel('\theta_2(f)', 'fontsize', 16);
title('Angular spectrum', 'fontsize', 16);